hbpc_tools_homepage:
    path:     /
    defaults: 
        _controller: HBPCToolsBundle:Home:index
hbpc_tools_categories:
    path:     /categories
    defaults: 
        _controller: HBPCToolsBundle:Categories:index
hbpc_tools_categories_new:
    path:   /categories/add
    defaults:
        _controller: HBPCToolsBundle:Categories:add
hbpc_tools_categories_view:
    path:   /categories/{id}
    defaults:
        _controller: HBPCToolsBundle:Categories:view
    requirements:
         id: \d+
hbpc_tools_categories_remove:
    path:   /categories/{id}/remove
    defaults:
        _controller: HBPCToolsBundle:Categories:remove
    requirements:
         id: \d+
hbpc_tools_composants:
    path:     /composants
    defaults: 
        _controller: HBPCToolsBundle:Composants:index
hbpc_tools_config:
    path:     /config
    defaults: 
        _controller: HBPCToolsBundle:Config:index
hbpc_tools_config_view:
    path:     /config/{id}
    defaults: 
        _controller: HBPCToolsBundle:Config:view
    requirements:
        id: \d+


