hbpc_tools:
    resource: "@HBPCToolsBundle/Resources/config/routing.yml"
    prefix:   /
    
login:
    path: /login
    defaults:
        _controller: HBPCUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout