# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_ADMIN]
    
    providers:
        in_memory:
            memory:
                users:
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main_login:
            pattern:   ^/login$
            anonymous: true 
        main:
            pattern:   ^/
            anonymous: false
            provider:     in_memory
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:       logout
                target:     /
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }