<?php

namespace HBPC\ToolsBundle\Repository;

/**
 * CategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\EntityRepository;

class CategorieRepository extends EntityRepository
{
    public function findAllSortASC(){
        $qb = $this->createQueryBuilder('c');
        $qb
            ->orderBy('c.position', 'ASC')
        ;
        return $qb->getQuery()->getResult();
    }
}
