<?php

namespace HBPC\ToolsBundle\Repository;

/**
 * ComposantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\EntityRepository;

class ComposantRepository extends EntityRepository
{
    public function findAllSortCat(){
        $qb = $this->createQueryBuilder('c');
        $qb
            ->orderBy('c.categorie', 'ASC')
        ;
        return $qb->getQuery()->getResult();
    }
    
    public function findAllByCategorie($id){
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.id = :id')
           ->setParameter('id', $id);
        return $qb->getQuery()->getResult();
    }
    
    public function findAllByConfig($id){
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.id = :id')
           ->setParameter('id', $id);
        return $qb->getQuery()->getResult();
    }
}
