<?php

namespace HBPC\ToolsBundle\Repository;

/**
 * ComposantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComposantsRepository extends \Doctrine\ORM\EntityRepository
{
}
