<?php

namespace HBPC\ToolsBundle\Repository;

/**
 * ConfigurationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\EntityRepository;

class ConfigurationRepository extends EntityRepository
{    
   
    public function findAllByConfigCustom($id){
        
        $qb = $this->createQueryBuilder('config')
                    ->join('config.composants', 'compos')
                    ->addSelect('compos')
                    ->join('compos.categorie', 'cat')
                    ->addSelect('cat')
                    ->where('config.id = :id')
                    ->setParameter('id', $id)
                    ->orderBy('cat.position', 'ASC')
                   ;
        return $qb->getQuery()->getResult();
    }
}
