<?php

namespace HBPC\ToolsBundle\Repository;

/**
 * ConfigurationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\EntityRepository;

class ConfigurationRepository extends \Doctrine\ORM\EntityRepository
{
    
    
}
