<?php

namespace HBPC\ToolsBundle\Repository;

/**
 * ConfigurationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigurationsRepository extends \Doctrine\ORM\EntityRepository
{
}
