<?php

namespace HBPC\ToolsBundle\Repository;

/**
 * ConfigCompoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigCompoRepository extends \Doctrine\ORM\EntityRepository
{
}
